# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('jobs', '0001_initial'), ('jobs', '0002_auto_20160124_2224'), ('jobs', '0003_job_url'), ('jobs', '0004_auto_20160125_1221'), ('jobs', '0005_auto_20160125_1350'), ('jobs', '0006_job_date_created'), ('jobs', '0007_auto_20160127_1529'), ('jobs', '0008_auto_20160127_2032')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Munka megnevezése')),
                ('job_type', models.IntegerField(choices=[(0, 'Könnyű fizikai'), (1, 'Irodai'), (2, 'Telefonos'), (3, 'Hostess'), (4, 'Műszaki'), (5, 'Informatikai'), (6, 'Áruházi/Vendéglátós'), (7, 'Egyéb')], db_index=True, verbose_name='Munka típusa')),
                ('task', models.TextField(verbose_name='Feladat leírása')),
                ('place_of_work', models.CharField(max_length=250, verbose_name='Munkavégzés helye')),
                ('min_salary', models.IntegerField(db_index=True, verbose_name='Minumum órabér')),
                ('max_salary', models.IntegerField(verbose_name='Maximum órabér')),
                ('working_hours', models.CharField(max_length=30, verbose_name='Munkaidő')),
                ('requirements', models.TextField(verbose_name='Feltételek')),
                ('other_info', models.CharField(blank=True, max_length=250, verbose_name='Egyéb információ')),
                ('url', models.CharField(default=None, max_length=250, verbose_name='Munka URL címe')),
                ('created', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 27, 19, 32, 35, 378485, tzinfo=utc), verbose_name='Hozzáadás dátuma')),
                ('modified', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 27, 19, 32, 59, 289443, tzinfo=utc), verbose_name='Módosítás dátuma')),
            ],
        ),
    ]
