# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20160128_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(null=True, verbose_name='Maximum órabér'),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Minumum órabér'),
        ),
    ]
