# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160128_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(default=1, verbose_name='Maximum órabér'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Minumum órabér'),
            preserve_default=False,
        ),
    ]
