# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160128_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.TextField(choices=[('konnyu_fizikai', 'Könnyű fizikai'), ('irodai', 'Irodai'), ('telefonos', 'Telefonos'), ('hostess', 'Hostess'), ('muszaki', 'Műszaki'), ('informatikai', 'Informatikai'), ('aruhazi_vendeglatos', 'Áruházi/Vendéglátós'), ('egyeb', 'Egyéb')], db_index=True, verbose_name='Munka típusa'),
        ),
    ]
