# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160202_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'Könnyű fizikai'), (1, 'Irodai'), (2, 'Telefonos'), (3, 'Hostess'), (4, 'Műszaki'), (5, 'Informatikai'), (6, 'Áruházi/Vendéglátós'), (7, 'Egyéb')], db_index=True, verbose_name='Munka típusa'),
        ),
    ]
