# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 22:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20160217_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Munka URL címe'),
        ),
    ]
