# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20160220_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Munka típusa')),
            ],
            options={
                'verbose_name': 'Munkatípus',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobProvider', verbose_name='Diákmunka Szövetkezet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType', verbose_name='Munka típusa'),
        ),
        migrations.AlterField(
            model_name='jobprovider',
            name='name',
            field=models.TextField(unique=True, verbose_name='Szövetkezet neve'),
        ),
    ]
