# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20160220_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Diákmunka', 'verbose_name_plural': 'Diákmunkák'},
        ),
        migrations.AlterModelOptions(
            name='jobprovider',
            options={'verbose_name': 'Diákmunka Szövetkezet', 'verbose_name_plural': 'Diákmunka Szövetkezetek'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Munkatípus', 'verbose_name_plural': 'Munkatípusok'},
        ),
    ]
