# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 23:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Hozzáadás dátuma')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Módosítás dátuma')),
                ('state', models.TextField(unique=True, verbose_name='Státusz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Hozzáadás dátuma')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Módosítás dátuma')),
                ('url', models.TextField(primary_key=True, serialize=False, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Munka URL címe')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.State', verbose_name='Scraping státusza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
