# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='scraped_data',
            field=models.TextField(default='', verbose_name='Scrapelt JSON'),
            preserve_default=False,
        ),
    ]
