# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_url_scraped_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='provider_name',
            field=models.TextField(default='ydiak', verbose_name='Diakszövetkezet rövid neve'),
            preserve_default=False,
        ),
    ]
