# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_url_provider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Hozzáadás dátuma')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Módosítás dátuma')),
                ('name', models.TextField(verbose_name='Diakszövetkezet rövid neve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='url',
            name='provider_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.Provider', verbose_name='Diakszövetkezet rövid neve'),
        ),
    ]
