# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_auto_20160311_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='provider_name',
            new_name='provider',
        ),
    ]
